language: python
python:
  - "2.7"
install:
  - "pip install -q yapsy==1.10.2-pythons2n3 err==2.0.0 --use-wheel"
  - "pip install -q coverage coveralls --use-wheel"
script:
  - coverage run --source=mathbot.py test_mathbot.py
after_success:
  - coveralls
notifications:
  email: false
